# Generated by Django 2.2.7 on 2019-11-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('bid_deadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('team_members', models.TextField(max_length=500)),
                ('phases_and_pricing', models.TextField(max_length=700)),
                ('total_price', models.CharField(max_length=100)),
                ('public_profile_urls', models.TextField(max_length=500)),
                ('work_sample_urls', models.TextField(max_length=500)),
                ('statement', models.TextField(max_length=600)),
                ('conditions', models.CharField(max_length=255)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(choices=[('191101', 'Holiday Digital (191101)'), ('190930', 'Non-Profit Video (190930)'), ('190711', 'Website & Digital Marketing (190711)')], on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='copro_bids.Project')),
            ],
        ),
    ]
